spring:
  application:
    name: usersystem
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:mariadb://localhost:3307/usersystem
    username: root
    password: diegousac17

  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    outOfOrder: true
    schemas: public
    enabled: true

